apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: api
spec:
  generators:
    - list:
        elements:
          - cluster: niydon-dev
            url: https://1.2.3.4
          - cluster: niydon-qa
            url: https://2.4.6.8
          - cluster: niydon-prod
            url: https://9.8.7.6
  template:
    metadata:
      name: "simple-api"
    spec:
      project: simple-api
      source:
        repoURL: https://github.com/doniyorniazov/refit-test.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/guestbook/{{cluster}}
      destination:
        server: "{{url}}"
        namespace: guestbook
