apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
    - clusters: {}
  template:
    metadata:
      name: "simpleapi"
    spec:
      project: "simpleapi"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: "{{.server}}"
        namespace: guestbook
