apiVersion: apps/v1
kind: Deployment
metadata: 
  name: simpleApi
  labels: 
    app: Simple API
spec: 
  replicas: 2
  selector: 
    matchlabels:
      service: simpleApi
  templplate: 
    metadata: 
      labels:
        app: simpleApi
        service: webapi 
    spec:
      containers:
        - name: simpleapi
          image: eaglebusinesssoftware.azurecr.io/simpleapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS 
              value: http://+:80
#      imagePullSecrets:
#        - name: eaglebusinesssoftware.azurecr.io