version: '3.4'

services:
  api:
    image: doniyozov/api
    build:
      context: .
      dockerfile: SimpleApi/Dockerfile
    environment:
      - "ASPNETCORE_URLS=http://+:80"
    ports:
      - "5001:80"