version: '3.4'

services:
  api:
    image: doniyozov/api:v1
    container_name: API
    build:
      context: .
      dockerfile: SimpleApi/Dockerfile
    environment:
      - "ASPNETCORE_URLS=http://+:80"
    ports:
      - "9003:80"

  webapp:
    image: doniyozov/webapp
    container_name: WebUI
    build: 
      context: .
      dockerfile: SimpleUI/Dockerfile
    depends_on:
      - api
    environment:
      - "ASPNETCORE_URLS=http://+:80"
      - "API_BASE_URL=http://webapp:80"
    ports:
      - "9001:80"
